name: Do some things

on:
  workflow_dispatch:
    inputs:
      target:
        description: "Do something a or something b"
        type: choice
        options:
          - "something a"
          - "something b"
        default: "something a"
        required: true

jobs:
  test-output:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: define variable
        run: echo "DEPLOY_ENVIRONMENT=$([[ ${{ github.event.inputs.target }} == 'something a' ]] && echo 'production' || echo 'beta')" >> $GITHUB_OUTPUT

      - name: test inputs
        run: echo ${{ steps.env.outputs.DEPLOY_ENVIRONMENT }}
