name: Do some things

on:
  workflow_dispatch:
    inputs:
      target:
        description: "Do something a or something b"
        type: choice
        options:
          - "something a"
          - "something b"
        default: "something a"
        required: true

jobs:
  setup:
    name: Set environment variables
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      DEPLOY_ENVIRONMENT: ${{ steps.env.outputs.DEPLOY_ENVIRONMENT }}
    steps:
      - name: "☁️ compute environment variables"
        id: env
        run: |
          echo "DEPLOY_ENVIRONMENT=$([[ ${{ inputs.target }} == 'something a' ]] && echo 'production' || echo 'beta')" >> $GITHUB_OUTPUT

  test-output:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - setup
    steps:
      - name: test inputs
        run: echo ${{ needs.setup.outputs.DEPLOY_ENVIRONMENT }}
